# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GraphStructure_config = debug
endif
ifeq ($(config),release)
  GraphStructure_config = release
endif

PROJECTS := GraphStructure

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GraphStructure:
ifneq (,$(GraphStructure_config))
	@echo "==== Building GraphStructure ($(GraphStructure_config)) ===="
	@${MAKE} --no-print-directory -C . -f GraphStructure.make config=$(GraphStructure_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f GraphStructure.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GraphStructure"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"